services:
  cartwebapi:
    image: ${DOCKER_REGISTRY-}cartwebapi
    build:
      context: .
      dockerfile: Cart Service/WebApi/Dockerfile

  catalogwebapi:
    image: ${DOCKER_REGISTRY-}catalogwebapi
    build:
      context: .
      dockerfile: Catalog Service/WebApi/Dockerfile
    depends_on:
      - db

  db:
    container_name: sql-server
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "password123!"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data: